"""Connection handling, DB path, sessions, and shared constants."""
from crm_db.core import (  # noqa: F401
    BANK_TX_TYPES,
    BOX_STATUS_OPTIONS,
    CASH_BOOK_TYPES,
    DB_PATH,
    DEFAULT_SETTINGS,
    ENTRY_TYPES,
    INVENTORY_STATUSES,
    NegativeBalanceWarning,
    PASSWORD_HASH_METHOD,
    RETURN_TYPES,
    USER_SCOPED_TABLES,
    VARIANT_OPTIONS,
    _column_exists,
    _local_date,
    _local_datetime,
    _normalize_datetime,
    _resolve_db_path,
    _table_exists,
    db_session,
    default_backup_dir,
    get_connection,
    init_db,
)

__all__ = [
    "BANK_TX_TYPES",
    "BOX_STATUS_OPTIONS",
    "CASH_BOOK_TYPES",
    "DB_PATH",
    "DEFAULT_SETTINGS",
    "ENTRY_TYPES",
    "INVENTORY_STATUSES",
    "NegativeBalanceWarning",
    "PASSWORD_HASH_METHOD",
    "RETURN_TYPES",
    "USER_SCOPED_TABLES",
    "VARIANT_OPTIONS",
    "_column_exists",
    "_local_date",
    "_local_datetime",
    "_normalize_datetime",
    "_resolve_db_path",
    "_table_exists",
    "db_session",
    "default_backup_dir",
    "get_connection",
    "init_db",
]

