"""Legacy idempotent _migrate_* chain for existing customer DBs."""
from crm_db.core import (  # noqa: F401
    _migrate_account_entry_payments,
    _migrate_cash_book_account,
    _migrate_credit_debit_convention,
    _migrate_cursor_panga,
    _migrate_devices,
    _migrate_expense_category_column,
    _migrate_fixed_expense_ledger,
    _migrate_indexes,
    _migrate_ledger_sync,
    _migrate_more_fixes,
    _migrate_multi_user,
    _migrate_payment_methods,
    _migrate_personal_assets,
    _migrate_phone_columns,
    _migrate_phone_statuses,
    _migrate_phones_table,
    _migrate_purchase_invoices,
    _migrate_remove_journal_vouchers,
    _migrate_returns_table,
    _migrate_side_investments,
    _migrate_unique_invoice_numbers,
)

__all__ = [
    "_migrate_account_entry_payments",
    "_migrate_cash_book_account",
    "_migrate_credit_debit_convention",
    "_migrate_cursor_panga",
    "_migrate_devices",
    "_migrate_expense_category_column",
    "_migrate_fixed_expense_ledger",
    "_migrate_indexes",
    "_migrate_ledger_sync",
    "_migrate_more_fixes",
    "_migrate_multi_user",
    "_migrate_payment_methods",
    "_migrate_personal_assets",
    "_migrate_phone_columns",
    "_migrate_phone_statuses",
    "_migrate_phones_table",
    "_migrate_purchase_invoices",
    "_migrate_remove_journal_vouchers",
    "_migrate_returns_table",
    "_migrate_side_investments",
    "_migrate_unique_invoice_numbers",
]

